image: python:2-alpine

stages:
  - test

unittests:
  stage: test
  script:
    - apk add --no-cache build-base curl postgresql-dev # for postgres-config
    - pip install -r requirements.txt
    - python -m unittest discover tests
