image: python:2-alpine

test:
  stage: test
  script:
    - apk add postgresql-dev --no-cache # for postgres-config
    - pip install -r requirements.txt
    - python -m unittest test_lodcc
  only:
    - 3-obtain-format-from-url-ending
