image: python:2-alpine

test:
  stage: test
  script:
    - apk add --no-cache build-base postgresql-dev # for postgres-config
    - pip install -r requirements.txt
    - python -m unittest test_lodcc
