image: python:2-alpine

stages:
  - install_dependencies
  - test_lodcc
  - test_lodcchelpers

install_dependencies:
  stage: install_dependencies
  script:
    - apk add --no-cache build-base postgresql-dev # for postgres-config
    - pip install -r requirements.txt

test_lodcc:
  stage: test_lodcc
  script:
    - python -m unittest test_lodcc

test_lodcchelpers:
  stage: test_lodcchelpers
  script:
    - python -m unittest test_lodcchelpers
