image: python:2-alpine

test:
  stage: test
  script:
    - apt-get update --quiet --assume-yes
    - apt-get install --quiet libpq-dev # for postgres-config
    - pip install -r requirements.txt
    - python -m unittest test_lodcc
  only:
    - 3-obtain-format-from-url-ending
